type: dockerfile
dockerfile: Dockerfile
port: 80
healthcheck:
  path: /
  interval: 30
  timeout: 10
  initial_delay: 40
env:
  - name: ASPNETCORE_ENVIRONMENT
    value: Production
  - name: ASPNETCORE_URLS
    value: http://+:80

